# include: package:flutter_lints/flutter.yaml
include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    curly_braces_in_flow_control_structures: true
    do_not_use_environment: true
    lines_longer_than_80_chars: false
    require_trailing_commas: true
    flutter_style_todos: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options.dart"
  errors:
    invalid_annotation_target: ignore

  # dart code metrics Basic configuration
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - no-magic-number:
        allowed: []
    - prefer-first
    - prefer-last
    - prefer-match-file-name
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - avoid-global-state
    - technical-debt:
        threshold: 1
        todo-cost: 161
        ignore-cost: 320
        ignore-for-file-cost: 396
        as-dynamic-cost: 322
        deprecated-annotations-cost: 37
        file-nullsafety-migration-cost: 41
        unit-type: "EUR"
